export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const IS_FETCHING = 'IS_FETCHING';
export const REQUEST_SUCESS = 'REQUEST_SUCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const SUBMIT_EDIT_EXPENSE = 'SUBMIT_EDIT_EXPENSE';
